[theme]
primaryColor = "#FF8C02"  # Bright Orange for buttons
backgroundColor = "#FFF8E1"  # Soft peach background
secondaryBackgroundColor = "#B3E5FC"  # Soft pastel blue sidebar
textColor = "#424242"  # Dark text for readability
font = "sans serif"  # Modern sans-serif font
